name: Macos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - name: Install
        run: ./install.sh

      - name: Restart shell
        run: |
          source ~/.zshrc
          git version
          python3 --version
          yarn --version
          yq --version
          jq --version
          helm version
          flux --version
          terraform --version
          sops --version
          aws --version
          node --version
          tree --version
          kubectl version --client
          wget --version
