name: Macos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: List files
        run: ls -la

      - name: Install
        run: ./install.sh

      - name: Restart shell
        run: source ~/.zshrc
